#Apache2 with php5 on Ubuntu 14.04 LTS
FROM nimmis/apache-php5

#Author
MAINTAINER PavelKlochkov <paul.klochkov@gmail.com>

#Copy our apache config
COPY default.conf /etc/apache2/sites-available/000-default.conf

#Open the container port
EXPOSE 80

#run the Apache server in the background
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

#install Ubuntu updates
RUN apt-get update

#run Apache rewrite mod for correct php routing
RUN a2enmod rewrite